### 모든 posts
GET https://jsonplaceholder.typicode.com/posts

### posts 특정 id 
GET https://jsonplaceholder.typicode.com/posts?id=1

### POST 쓰기
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json 

{
  "userId": 1,
  "title": "test",
  "body": "test"
}

### POST 삭제
DELETE https://jsonplaceholder.typicode.com/posts/10

### POST 전체 수정
PUT https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
  "userId": 200,
  "title": "one",
  "body": "one"
}

### POST 일부 수정
PATCH https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
  "title": "test"
}
